In [36]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [37]:
batch_size, n_classes = 5, 3
x = torch.randn(batch_size, n_classes)
x.shape

torch.Size([5, 3])

In [38]:
x

tensor([[-1.3317, -1.1794,  0.1294],
        [ 1.4887,  0.2633, -0.9879],
        [-0.2142,  0.7699, -0.0327],
        [ 0.0253,  1.0539, -0.8399],
        [-0.1088, -0.2115, -1.5548]])

In [39]:
target = torch.randint(n_classes, size=(batch_size,), dtype=torch.long)
target


tensor([2, 0, 2, 2, 0])

softmax+(nl)negative likelihood

In [40]:
def softmax(x): return x.exp() / (x.exp().sum(-1)).unsqueeze(-1)
def nl(input, target): return -input[range(target.shape[0]), target].log().mean()

pred = softmax(x)
print(-pred[range(target.shape[0]), target].log())
print(pred)
loss=nl(pred, target)
loss

tensor([0.4069, 0.3204, 1.4025, 2.3046, 0.7598])
tensor([[0.1544, 0.1798, 0.6657],
        [0.7259, 0.2131, 0.0610],
        [0.2052, 0.5489, 0.2460],
        [0.2371, 0.6631, 0.0998],
        [0.4678, 0.4221, 0.1102]])


tensor(1.0388)

In [41]:
pred = softmax(x)
loss=nl(pred, target)
loss

tensor(1.0388)

log_softmax + nll (negative log-likelihood)

In [42]:
def log_softmax(x): return x - x.exp().sum(-1).log().unsqueeze(-1)
def nll(input, target): return -input[range(target.shape[0]), target].mean()

pred = log_softmax(x)
loss = nll(pred, target)
loss

tensor(1.0388)

F.log_softmax + F.nll_loss

In [43]:
pred = F.log_softmax(x, dim=-1)
loss = F.nll_loss(pred, target)
loss

tensor(1.0388)

F.cross_entropy

In [44]:
F.cross_entropy(x, target)

tensor(1.0388)